[package]
authors = ["Trevor Pierce <yeahtrevorpierce@gmail.com>"]
edition = "2018"
name = "time_clock"
version = "0.1.0"

[dependencies]
async-std = {version = "1.6", features = ["attributes"]}
clap = "2.33.3"
sqlx = {version = "0.5.1", features = ["postgres", "runtime-async-std-native-tls"]}
