[package]
name = "time_clock"
version = "0.1.0"
authors = ["Trevor Pierce <yeahtrevorpierce@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.5", features = ["postgres"] }
dotenv = "0.15.0"
structopt = "0.3.15"